// client/src/app/static/components/button/button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type ButtonVariant = 'text' | 'filled' | 'outlined';
export type ButtonColor = 'primary' | 'warn' | '';

@Component({
  selector: 'app-button',
  template: `
    <button
      [type]="type()"
      [disabled]="disabled() || null"
      class="w-full h-full bg-transparent border-0 cursor-pointer inline-flex items-center justify-center gap-2 font-[inherit] text-[inherit] outline-none disabled:opacity-40 disabled:cursor-not-allowed">
      <ng-content />
    </button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass()',
    '[attr.aria-disabled]': 'disabled() || null',
  },
  imports: [],
})
export class ButtonComponent {
  readonly iconOnly = input<boolean | string>(false);
  readonly variant = input<ButtonVariant>('text');
  readonly color = input<ButtonColor>('primary');
  readonly disabled = input(false);
  readonly type = input<'button' | 'submit' | 'reset'>('button');

  readonly hostClass = computed(() => {
    const base = 'inline-flex items-center justify-center transition-colors';

    if (this.iconOnly()) {
      const color = this.color();

      if (color === 'warn') {
        return `${base} h-10 w-10 rounded-full text-warn hover:bg-warn/8`;
      }

      if (color === 'primary') {
        return `${base} h-10 w-10 rounded-full text-primary hover:bg-primary/8`;
      }

      return `${base} h-10 w-10 rounded-full hover:bg-foreground/8`;
    }

    const sizing = 'h-9 px-4 text-sm font-medium rounded';
    const color = this.color();
    const variant = this.variant();

    if (variant === 'filled') {
      return color === 'warn'
        ? `${base} ${sizing} bg-warn text-white hover:bg-warn/90`
        : `${base} ${sizing} bg-primary text-white hover:bg-primary/90`;
    }

    if (variant === 'outlined') {
      return color === 'warn'
        ? `${base} ${sizing} border border-warn text-warn hover:bg-warn/8`
        : `${base} ${sizing} border border-primary text-primary hover:bg-primary/8`;
    }

    if (!color) {
      return `${base} ${sizing} text-foreground hover:bg-foreground/8`;
    }

    return color === 'warn'
      ? `${base} ${sizing} text-warn hover:bg-warn/8`
      : `${base} ${sizing} text-primary hover:bg-primary/8`;
  });
}

// website/src/components/Button.tsx
import type { JSX } from 'solid-js';
import { Show, splitProps } from 'solid-js';

type Variant = 'primary' | 'outline' | 'ghost';
type Size = 'sm' | 'md' | 'lg';

type ButtonProps = {
  variant?: Variant;
  size?: Size;
  href?: string;
  class?: string;
  children: JSX.Element;
} & JSX.ButtonHTMLAttributes<HTMLButtonElement>;

const variantClasses: Record<Variant, string> = {
  primary: 'bg-brand hover:bg-brand-dark text-white hover:bg-brand-dark shadow-sm',
  outline:
    'border border-slate-300 text-slate-800 hover:border-brand hover:text-brand bg-white dark:border-white/20 dark:text-white dark:bg-transparent dark:hover:border-brand dark:hover:text-brand',
  ghost:
    'text-slate-600 hover:text-brand hover:bg-violet-50 dark:text-white/60 dark:hover:text-brand dark:hover:bg-violet-500/10',
};

const sizeClasses: Record<Size, string> = {
  sm: 'px-4 py-2 text-sm',
  md: 'px-5 py-2.5 text-sm',
  lg: 'px-6 py-3 text-base',
};

export default function Button(props: ButtonProps) {
  const [local, rest] = splitProps(props, ['variant', 'size', 'href', 'class', 'children']);

  const variant = () => local.variant ?? 'primary';
  const size = () => local.size ?? 'md';

  const classes = () =>
    `inline-flex items-center justify-center gap-2 rounded font-medium transition-colors cursor-pointer ${variantClasses[variant()]} ${sizeClasses[size()]} ${local.class ?? ''}`;

  return (
    <Show
      when={local.href}
      fallback={
        <button class={classes()} {...rest}>
          {local.children}
        </button>
      }
    >
      <a href={local.href} class={classes()}>
        {local.children}
      </a>
    </Show>
  );
}
